# Generated by Django 6.0.2 on 2026-02-13 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_task_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome do projeto', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada do projeto')),
                ('status', models.CharField(choices=[('planning', 'Planejamento'), ('active', 'Ativo'), ('completed', 'Concluído'), ('archived', 'Arquivado')], default='planning', help_text='Status atual do projeto', max_length=20)),
                ('start_date', models.DateField(blank=True, help_text='Data de início do projeto', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Data de conclusão do projeto', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta')], default='medium', help_text='Prioridade da tarefa', max_length=10),
        ),
        migrations.AlterField(
            model_name='task',
            name='completed',
            field=models.BooleanField(default=False, help_text='Indica se a tarefa foi concluída'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(help_text='Descrição detalhada da tarefa'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='Título da tarefa', max_length=200),
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, help_text='Projeto ao qual esta tarefa pertence', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='core.project'),
        ),
    ]
